openapi: 3.0.2
info:
  title: The OGC API - Processes
  version: 1.0-draft.6-SNAPSHOT
  description: |-
    WARNING - THIS IS WORK IN PROGRESS
  contact:
    name: Benjamin Pross
    email: b.pross@52north.org
  license:
    name: OGC license
    url: "https://raw.githubusercontent.com/opengeospatial/ogcapi-processes/master/LICENSE"
paths:
  /:
    get:
      summary: landing page of this API
      description: >-
        The landing page provides links to the API definition, the conformance
        declaration and the metadata about the processes offered by this service.
      operationId: getLandingPage
      tags:
        - Capabilities
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/LandingPage.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
  /conformance:
    get:
      summary: information about standards that this API conforms to
      description: >-
        Lists all requirements classes specified in the standard (e.g., OGC API - Processes
        Part 1: Core) that the server conforms to
      operationId: getConformanceClasses
      tags:
        - ConformanceDeclaration
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ConformanceDeclaration.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
  /processes:
    get:
      summary: retrieve the list of available processes
      description: >-
        Lists all available processes this server offers.
      operationId: getProcesses
      tags:
        - ProcessList
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ProcessList.yaml"
  /processes/{processId}:
    get:
      summary: retrieve a process description
      description: >-
        Describes a process.
      operationId: getProcessDescription
      tags:
        - ProcessDescription
      parameters:
        - $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/parameters/processId.yaml"
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ProcessDescription.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
  /jobs:
    get:
      summary: retrieve the list of jobs for a process.
      description: >-
        Lists available jobs.
      operationId: getJobs
      tags:
        - JobList
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/JobList.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
    post:
      summary: execute a process.
      description: >-
        Submits a new job.
      operationId: execute
      tags:
        - Execute
      requestBody:
        description: Mandatory execute request JSON
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/schemas/execute.yaml"
      responses:
        200:
          $ref: 'https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ExecuteSync.yaml'
        201:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ExecuteAsync.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
      callbacks:
        jobCompleted:
          "{$request.body#/subscriber/successUri}":
            post:
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/schemas/result.yaml"
              responses:
                200:
                  description: Results received successfully
  /jobs/{jobId}:
    get:
      summary: retrieve the status of a job
      description: >-
        Shows the status of a job.
      operationId: getStatus
      tags:
        - Status
      parameters:
        - $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/parameters/jobId.yaml"
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/Status.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
    delete:
      summary: cancel a job execution, remove a finished job
      description: >-
        Cancel a job execution and remove it from the jobs list.
      operationId: dismiss
      tags:
        - Dismiss
      parameters:
        - $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/parameters/jobId.yaml"
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/Status.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
  /jobs/{jobId}/results:
    get:
      summary: retrieve the result(s) of a job
      description: >-
        Lists available results of a job. In case of a failure, lists exceptions instead.
      operationId: getResult
      tags:
        - Result
      parameters:
        - $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/parameters/jobId.yaml"
      responses:
        200:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/Results.yaml"
        404:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/NotFound.yaml"
        500:
          $ref: "https://raw.githubusercontent.com/bpross-52n/ogcapi-processes/reftest/core/openapi/responses/ServerError.yaml"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/bpross-52n/api-processes-reftest/1.0-draft.6-SNAPSHOT
  - description: 52°North demo server
    url: http://geoprocessing.demo.52north.org:8080/javaps/rest/